version: "3.8" #compatible with docker engine 19.03+

services:
  node_app:
    container_name: node_app
    build: ./ # dockerfile path
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    links:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongodb/mongodb-community-server:4.4.21-ubi8
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=user
    #   - MONGO_INITDB_ROOT_PASSWORD=pass
    #   # - MONGO_INITDB_DATABASE=climateDB
    # volumes: # to persist data across containers startups ## remove 'mongo_seed' service ##
    #   - type: bind
    #     source: ./data
    #     target: /data/db
    ports:
      - 27017:27017

  mongo_seed:
    container_name: mongo_seed
    build: ./mongo-seed # dockerfile path
    depends_on:
      - mongodb
